package com.linkany121.gltc.logic.credit;

import java.util.List;
import java.util.Map;

/** Energy-flow shop listings ported from scripts/能源流. */
public final class EnergyShopCatalog {
    private EnergyShopCatalog() {}

    public record Offer(String type, String id, String priceId, int priceAmt, int giveAmount, int limit) {}
    public record Shop(String id, String title, int batchMultiplier, String usageLine, List<Offer> items) {}

    /** 与 scripts/能源流/*.js 的 ITEM_NAMES 保持一致的中文名映射（仅用于聊天消息）。 */
    public static final Map<String, String> ITEM_NAMES = Map.ofEntries(  // 原版物品/材料 ID → 中文名（仅用于聊天消息）
        Map.entry("OAK_SAPLING", "橡树树苗"),
        Map.entry("SPRUCE_SAPLING", "云杉树苗"),
        Map.entry("BIRCH_SAPLING", "白桦树苗"),
        Map.entry("JUNGLE_SAPLING", "丛林树苗"),
        Map.entry("ACACIA_SAPLING", "金合欢树苗"),
        Map.entry("DARK_OAK_SAPLING", "深色橡树苗"),
        Map.entry("CHERRY_SAPLING", "樱花树苗"),
        Map.entry("MANGROVE_PROPAGULE", "红树胎生苗"),
        Map.entry("AZALEA", "杜鹃花丛"),
        Map.entry("FLOWERING_AZALEA", "盛开的杜鹃花丛"),
        Map.entry("CRIMSON_FUNGUS", "绯红菌"),
        Map.entry("WARPED_FUNGUS", "诡异菌"),
        Map.entry("POPPY", "虞美人"),
        Map.entry("DANDELION", "蒲公英"),
        Map.entry("BLUE_ORCHID", "兰花"),
        Map.entry("ALLIUM", "绒球葱"),
        Map.entry("AZURE_BLUET", "蓝花美耳草"),
        Map.entry("OXEYE_DAISY", "滨菊"),
        Map.entry("CORNFLOWER", "矢车菊"),
        Map.entry("RED_TULIP", "红色郁金香"),
        Map.entry("ORANGE_TULIP", "橙色郁金香"),
        Map.entry("WHITE_TULIP", "白色郁金香"),
        Map.entry("PINK_TULIP", "粉红色郁金香"),
        Map.entry("LILY_OF_THE_VALLEY", "铃兰"),
        Map.entry("SUNFLOWER", "向日葵"),
        Map.entry("LILAC", "丁香"),
        Map.entry("ROSE_BUSH", "玫瑰丛"),
        Map.entry("PEONY", "牡丹"),
        Map.entry("PITCHER_PLANT", "瓶子草"),
        Map.entry("TORCHFLOWER", "火把花"),
        Map.entry("PINK_PETALS", "粉红色花簇"),
        Map.entry("CHORUS_FLOWER", "紫颂花"),
        Map.entry("SPORE_BLOSSOM", "孢子花"),
        Map.entry("WITHER_ROSE", "凋零玫瑰"),
        Map.entry("BROWN_MUSHROOM", "棕色蘑菇"),
        Map.entry("RED_MUSHROOM", "红色蘑菇"),
        Map.entry("WHEAT_SEEDS", "小麦种子"),
        Map.entry("PUMPKIN_SEEDS", "南瓜种子"),
        Map.entry("MELON_SEEDS", "西瓜种子"),
        Map.entry("BEETROOT_SEEDS", "甜菜种子"),
        Map.entry("TORCHFLOWER_SEEDS", "火把花种子"),
        Map.entry("PITCHER_POD", "瓶子草荚果"),
        Map.entry("NETHER_WART", "下界疣"),
        Map.entry("COCOA_BEANS", "可可豆"),
        Map.entry("CARROT", "胡萝卜"),
        Map.entry("POTATO", "马铃薯"),
        Map.entry("WHEAT", "小麦"),
        Map.entry("BEETROOT", "甜菜根"),
        Map.entry("APPLE", "苹果"),
        Map.entry("MELON_SLICE", "西瓜片"),
        Map.entry("PUMPKIN", "南瓜"),
        Map.entry("MELON", "西瓜"),
        Map.entry("SWEET_BERRIES", "甜浆果"),
        Map.entry("GLOW_BERRIES", "发光浆果"),
        Map.entry("BAMBOO", "竹子"),
        Map.entry("SUGAR_CANE", "甘蔗"),
        Map.entry("CACTUS", "仙人掌"),
        Map.entry("SEA_PICKLE", "海泡菜"),
        Map.entry("CHORUS_FRUIT", "紫颂果"),
        Map.entry("SHORT_GRASS", "矮草丛"),
        Map.entry("TALL_GRASS", "高草丛"),
        Map.entry("FERN", "蕨"),
        Map.entry("LARGE_FERN", "大型蕨"),
        Map.entry("VINE", "藤蔓"),
        Map.entry("LILY_PAD", "睡莲"),
        Map.entry("MOSS_BLOCK", "苔藓块"),
        Map.entry("MOSS_CARPET", "苔藓地毯"),
        Map.entry("BIG_DRIPLEAF", "大型垂滴叶"),
        Map.entry("SMALL_DRIPLEAF", "小型垂滴叶"),
        Map.entry("GLOW_LICHEN", "发光地衣"),
        Map.entry("HANGING_ROOTS", "垂根"),
        Map.entry("SEAGRASS", "海草"),
        Map.entry("KELP", "海带"),
        Map.entry("OAK_LEAVES", "橡树树叶"),
        Map.entry("SPRUCE_LEAVES", "云杉树叶"),
        Map.entry("BIRCH_LEAVES", "白桦树叶"),
        Map.entry("JUNGLE_LEAVES", "丛林树叶"),
        Map.entry("ACACIA_LEAVES", "金合欢树叶"),
        Map.entry("DARK_OAK_LEAVES", "深色橡树叶"),
        Map.entry("CHERRY_LEAVES", "樱花树叶"),
        Map.entry("MANGROVE_LEAVES", "红树树叶"),
        Map.entry("AZALEA_LEAVES", "杜鹃树叶"),
        Map.entry("FLOWERING_AZALEA_LEAVES", "盛开的杜鹃树叶"),
        Map.entry("CRIMSON_ROOTS", "绯红菌索"),
        Map.entry("WARPED_ROOTS", "诡异菌索"),
        Map.entry("WEEPING_VINES", "垂泪藤"),
        Map.entry("TWISTING_VINES", "缠怨藤"),
        Map.entry("MANGROVE_ROOTS", "红树根"),
        Map.entry("DEAD_BUSH", "枯死的灌木"),
        Map.entry("COAL", "煤炭"),
        Map.entry("REDSTONE", "红石粉"),
        Map.entry("LAPIS_LAZULI", "青金石"),
        Map.entry("QUARTZ", "下界石英"),
        Map.entry("COPPER_INGOT", "铜锭"),
        Map.entry("IRON_INGOT", "铁锭"),
        Map.entry("GOLD_INGOT", "金锭"),
        Map.entry("AMETHYST_SHARD", "紫水晶碎片"),
        Map.entry("DIAMOND", "钻石"),
        Map.entry("EMERALD", "绿宝石"),
        Map.entry("NETHERITE_SCRAP", "下界合金碎片"),
        Map.entry("NETHERITE_INGOT", "下界合金锭"),
        Map.entry("COAL_ORE", "煤矿石"),
        Map.entry("COPPER_ORE", "铜矿石"),
        Map.entry("IRON_ORE", "铁矿石"),
        Map.entry("GOLD_ORE", "金矿石"),
        Map.entry("REDSTONE_ORE", "红石矿石"),
        Map.entry("LAPIS_ORE", "青金石矿石"),
        Map.entry("DIAMOND_ORE", "钻石矿石"),
        Map.entry("EMERALD_ORE", "绿宝石矿石"),
        Map.entry("NETHER_QUARTZ_ORE", "下界石英矿石"),
        Map.entry("NETHER_GOLD_ORE", "下界金矿石"),
        Map.entry("ANCIENT_DEBRIS", "远古残骸"),
        Map.entry("ROTTEN_FLESH", "腐肉"),
        Map.entry("BONE", "骨头"),
        Map.entry("STRING", "线"),
        Map.entry("ARROW", "箭"),
        Map.entry("FEATHER", "羽毛"),
        Map.entry("INK_SAC", "墨囊"),
        Map.entry("LEATHER", "皮革"),
        Map.entry("SPIDER_EYE", "蜘蛛眼"),
        Map.entry("GUNPOWDER", "火药"),
        Map.entry("SLIME_BALL", "粘液球"),
        Map.entry("MAGMA_CREAM", "岩浆膏"),
        Map.entry("PRISMARINE_SHARD", "海晶碎片"),
        Map.entry("PRISMARINE_CRYSTALS", "海晶砂粒"),
        Map.entry("GLOW_INK_SAC", "荧光墨囊"),
        Map.entry("RABBIT_HIDE", "兔子皮"),
        Map.entry("ENDER_PEARL", "末影珍珠"),
        Map.entry("NAUTILUS_SHELL", "鹦鹉螺壳"),
        Map.entry("RABBIT_FOOT", "兔子脚"),
        Map.entry("BLAZE_ROD", "烈焰棒"),
        Map.entry("PHANTOM_MEMBRANE", "幻翼膜"),
        Map.entry("GHAST_TEAR", "恶魂之泪"),
        Map.entry("SHULKER_SHELL", "潜影壳"),
        Map.entry("SPONGE", "海绵"),
        Map.entry("WITHER_SKELETON_SKULL", "凋零骷髅头颅"),
        Map.entry("TRIDENT", "三叉戟"),
        Map.entry("CHICKEN", "生鸡肉"),
        Map.entry("BEEF", "生牛肉"),
        Map.entry("PORKCHOP", "生猪排"),
        Map.entry("MUTTON", "生羊肉"),
        Map.entry("RABBIT", "生兔肉"),
        Map.entry("COD", "生鳕鱼"),
        Map.entry("SALMON", "生鲑鱼"),
        Map.entry("PUFFERFISH", "河豚"),
        Map.entry("TROPICAL_FISH", "热带鱼"),
        Map.entry("PAPER", "纸"),
        Map.entry("SUGAR", "糖"),
        Map.entry("STICK", "木棍"),
        Map.entry("BOWL", "碗"),
        Map.entry("GLASS_BOTTLE", "玻璃瓶"),
        Map.entry("BUCKET", "桶"),
        Map.entry("WATER_BUCKET", "水桶"),
        Map.entry("LAVA_BUCKET", "熔岩桶"),
        Map.entry("MILK_BUCKET", "牛奶桶"),
        Map.entry("NAME_TAG", "命名牌"),
        Map.entry("SADDLE", "鞍"),
        Map.entry("BELL", "钟"),
        Map.entry("BOOK", "书"),
        Map.entry("LEAD", "拴绳"),
        Map.entry("HONEYCOMB", "蜜脾"),
        Map.entry("HONEY_BOTTLE", "蜂蜜瓶"),
        Map.entry("SNOWBALL", "雪球"),
        Map.entry("CLAY_BALL", "粘土球"),
        Map.entry("BRICK", "红砖"),
        Map.entry("NETHER_BRICK", "下界砖"),
        Map.entry("FLINT", "燧石"),
        Map.entry("GLOWSTONE_DUST", "萤石粉"),
        Map.entry("BLAZE_POWDER", "烈焰粉"),
        Map.entry("FERMENTED_SPIDER_EYE", "发酵蛛眼"),
        Map.entry("DRAGON_BREATH", "龙息"),
        Map.entry("EXPERIENCE_BOTTLE", "附魔之瓶"),
        Map.entry("FIREWORK_ROCKET", "烟花火箭"),
        Map.entry("STONE", "石头"),
        Map.entry("DIRT", "泥土"),
        Map.entry("SAND", "沙子"),
        Map.entry("RED_SAND", "红沙"),
        Map.entry("GRAVEL", "沙砾"),
        Map.entry("COBBLESTONE", "圆石"),
        Map.entry("COBBLED_DEEPSLATE", "深板岩圆石"),
        Map.entry("OBSIDIAN", "黑曜石"),
        Map.entry("CRYING_OBSIDIAN", "哭泣的黑曜石"),
        Map.entry("ICE", "冰"),
        Map.entry("CALCITE", "方解石"),
        Map.entry("TUFF", "凝灰岩"),
        Map.entry("ANDESITE", "安山岩"),
        Map.entry("DIORITE", "闪长岩"),
        Map.entry("GRANITE", "花岗岩"),
        Map.entry("SANDSTONE", "砂岩"),
        Map.entry("RED_SANDSTONE", "红砂岩"),
        Map.entry("NETHERRACK", "下界岩"),
        Map.entry("SOUL_SAND", "灵魂沙"),
        Map.entry("SOUL_SOIL", "灵魂土"),
        Map.entry("BLACKSTONE", "黑石"),
        Map.entry("BASALT", "玄武岩"),
        Map.entry("END_STONE", "末地石"),
        Map.entry("GLOWSTONE", "萤石"),
        Map.entry("SEA_LANTERN", "海晶灯"),
        Map.entry("MAGMA_BLOCK", "岩浆块"),
        Map.entry("OCHRE_FROGLIGHT", "赭黄蛙明灯"),
        Map.entry("VERDANT_FROGLIGHT", "翠绿蛙明灯"),
        Map.entry("PEARLESCENT_FROGLIGHT", "珠光蛙明灯"),
        Map.entry("BUDDING_AMETHYST", "紫水晶母岩"),
        Map.entry("SCULK", "幽匿块"),
        Map.entry("SCULK_CATALYST", "幽匿催发体"),
        Map.entry("SCULK_SHRIEKER", "幽匿尖啸体"),
        Map.entry("SCULK_SENSOR", "幽匿感测体"),
        Map.entry("SCULK_VEIN", "幽匿脉络"),
        Map.entry("CLAY", "粘土块"),
        Map.entry("SNOW_BLOCK", "雪块"),
        Map.entry("PACKED_ICE", "浮冰"),
        Map.entry("BLUE_ICE", "蓝冰"),
        Map.entry("BONE_BLOCK", "骨块"),
        Map.entry("BOOKSHELF", "书架"),
        Map.entry("TNT", "TNT"),
        Map.entry("NOTE_BLOCK", "音符盒"),
        Map.entry("JUKEBOX", "唱片机"),
        Map.entry("LODESTONE", "磁石"),
        Map.entry("RESPAWN_ANCHOR", "重生锚"),
        Map.entry("GRASS_BLOCK", "草方块"),
        Map.entry("COARSE_DIRT", "砂土"),
        Map.entry("DEEPSLATE", "深板岩"),
        Map.entry("PODZOL", "灰化土"),
        Map.entry("MYCELIUM", "菌丝"),
        Map.entry("CRIMSON_NYLIUM", "绯红菌岩"),
        Map.entry("WARPED_NYLIUM", "诡异菌岩"),
        Map.entry("ROOTED_DIRT", "缠根泥土"),
        Map.entry("MUD", "泥巴"),
        Map.entry("MUDDY_MANGROVE_ROOTS", "沾泥的红树根"),
        Map.entry("DRIPSTONE_BLOCK", "滴水石块"),
        Map.entry("POINTED_DRIPSTONE", "滴水石锥"),
        Map.entry("NETHER_WART_BLOCK", "下界疣块"),
        Map.entry("WARPED_WART_BLOCK", "诡异疣块"),
        Map.entry("DRIED_KELP_BLOCK", "干海带块"),
        Map.entry("AMETHYST_BLOCK", "紫水晶块"),
        Map.entry("QUARTZ_BLOCK", "石英块"),
        Map.entry("HONEYCOMB_BLOCK", "蜜脾块"),
        Map.entry("HONEY_BLOCK", "蜂蜜块"),
        Map.entry("SLIME_BLOCK", "黏液块"),
        Map.entry("GILDED_BLACKSTONE", "镶金黑石"),
        Map.entry("SHROOMLIGHT", "菌光体"),
        Map.entry("ENERGY_REGULATOR", "能源调节器"),
        Map.entry("ENERGY_CONNECTOR", "能源连接器"),
        Map.entry("COAL_GENERATOR", "煤炭发电机")
    );

    // ===== 配置区（能源商店商品目录，改完需重新打包 jar 并重启生效）=====
    // 每项 Shop(id, 标题, 批量倍数, 说明, 商品列表)，其中商品 Offer(类型, 物品ID, 货币ID, 单价△, 单次购买数量, 购买上限)。
    //   - 货币ID 与 CreditService.SHOP_EXCHANGE_RATES 对应；type=vanilla 为原版物品，slimefun 为粘液科技物品。
    //   - 购买上限 0 = 不限购，>0 为每人最多购买次数（存档记录）。
    // 改动方式：增删 Shop/Offer 条目即可；Shift 批量购买数量 = 单价 × batchMultiplier。
    public static final Map<String, Shop> SHOPS = Map.ofEntries(
        Map.entry("plants", new Shop("plants", "§x§7§7§f§7§f§f协§x§6§0§f§a§d§a议§x§4§9§f§d§b§5内§x§6§3§f§f§9§3容§x§b§0§f§f§7§5：§x§f§c§f§f§5§7植物", 2, "§7点击即购买1个，Shift+点击直接购买64个。", List.of(
            new Offer("vanilla", "OAK_SAPLING", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "SPRUCE_SAPLING", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "BIRCH_SAPLING", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "JUNGLE_SAPLING", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "ACACIA_SAPLING", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "DARK_OAK_SAPLING", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "CHERRY_SAPLING", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "MANGROVE_PROPAGULE", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "AZALEA", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "FLOWERING_AZALEA", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "CRIMSON_FUNGUS", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "WARPED_FUNGUS", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "POPPY", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "DANDELION", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "BLUE_ORCHID", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "ALLIUM", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "AZURE_BLUET", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "OXEYE_DAISY", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "CORNFLOWER", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "RED_TULIP", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "ORANGE_TULIP", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "WHITE_TULIP", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "PINK_TULIP", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "LILY_OF_THE_VALLEY", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "SUNFLOWER", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "LILAC", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "ROSE_BUSH", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "PEONY", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "PITCHER_PLANT", "AL_A3", 12, 1, 0),
            new Offer("vanilla", "TORCHFLOWER", "AL_A3", 12, 1, 0),
            new Offer("vanilla", "PINK_PETALS", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "CHORUS_FLOWER", "AL_A3", 12, 1, 0),
            new Offer("vanilla", "SPORE_BLOSSOM", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "WITHER_ROSE", "AL_A3", 12, 1, 0),
            new Offer("vanilla", "BROWN_MUSHROOM", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "RED_MUSHROOM", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "WHEAT_SEEDS", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "PUMPKIN_SEEDS", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "MELON_SEEDS", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "BEETROOT_SEEDS", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "TORCHFLOWER_SEEDS", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "PITCHER_POD", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "NETHER_WART", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "COCOA_BEANS", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "CARROT", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "POTATO", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "WHEAT", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "BEETROOT", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "APPLE", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "MELON_SLICE", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "PUMPKIN", "AL_A3", 12, 1, 0),
            new Offer("vanilla", "MELON", "AL_A3", 12, 1, 0),
            new Offer("vanilla", "SWEET_BERRIES", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "GLOW_BERRIES", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "BAMBOO", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "SUGAR_CANE", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "CACTUS", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "SEA_PICKLE", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "CHORUS_FRUIT", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "SHORT_GRASS", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "TALL_GRASS", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "FERN", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "LARGE_FERN", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "VINE", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "LILY_PAD", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "MOSS_BLOCK", "AL_A3", 12, 1, 0),
            new Offer("vanilla", "MOSS_CARPET", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "BIG_DRIPLEAF", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "SMALL_DRIPLEAF", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "GLOW_LICHEN", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "HANGING_ROOTS", "AL_A3", 6, 1, 0),
            new Offer("vanilla", "SEAGRASS", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "KELP", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "OAK_LEAVES", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "SPRUCE_LEAVES", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "BIRCH_LEAVES", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "JUNGLE_LEAVES", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "ACACIA_LEAVES", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "DARK_OAK_LEAVES", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "CHERRY_LEAVES", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "MANGROVE_LEAVES", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "AZALEA_LEAVES", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "FLOWERING_AZALEA_LEAVES", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "CRIMSON_ROOTS", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "WARPED_ROOTS", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "WEEPING_VINES", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "TWISTING_VINES", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "MANGROVE_ROOTS", "AL_A3", 2, 1, 0),
            new Offer("vanilla", "DEAD_BUSH", "AL_A3", 2, 1, 0)
        ))),
        Map.entry("minerals", new Shop("minerals", "§x§7§7§f§7§f§f协§x§6§0§f§a§d§a议§x§4§9§f§d§b§5内§x§6§3§f§f§9§3容§x§b§0§f§f§7§5：§x§f§c§f§f§5§7矿物", 3, "§7点击即购买1次（获得标注数量），Shift+点击直接购买64个。", List.of(
            new Offer("vanilla", "COAL", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "REDSTONE", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "LAPIS_LAZULI", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "QUARTZ", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "COPPER_INGOT", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "IRON_INGOT", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "GOLD_INGOT", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "AMETHYST_SHARD", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "DIAMOND", "AL_A1", 12, 1, 0),
            new Offer("vanilla", "EMERALD", "AL_A1", 12, 1, 0),
            new Offer("vanilla", "ANCIENT_DEBRIS", "AL_A1", 64, 1, 0),
            new Offer("vanilla", "NETHERITE_SCRAP", "AL_A1", 32, 1, 0),
            new Offer("vanilla", "NETHERITE_INGOT", "AL_A1", 128, 1, 0),
            new Offer("vanilla", "COAL_ORE", "AL_A1", 80, 1, 0),
            new Offer("vanilla", "COPPER_ORE", "AL_A1", 80, 1, 0),
            new Offer("vanilla", "IRON_ORE", "AL_A1", 80, 1, 0),
            new Offer("vanilla", "GOLD_ORE", "AL_A1", 80, 1, 0),
            new Offer("vanilla", "REDSTONE_ORE", "AL_A1", 80, 1, 0),
            new Offer("vanilla", "LAPIS_ORE", "AL_A1", 80, 1, 0),
            new Offer("vanilla", "DIAMOND_ORE", "AL_A1", 80, 1, 0),
            new Offer("vanilla", "EMERALD_ORE", "AL_A1", 80, 1, 0),
            new Offer("vanilla", "NETHER_QUARTZ_ORE", "AL_A1", 80, 1, 0),
            new Offer("vanilla", "NETHER_GOLD_ORE", "AL_A1", 80, 1, 0)
        ))),
        Map.entry("drops", new Shop("drops", "§x§7§7§f§7§f§f协§x§6§0§f§a§d§a议§x§4§9§f§d§b§5内§x§6§3§f§f§9§3容§x§b§0§f§f§7§5：§x§f§c§f§f§5§7掉落物", 5, "§7点击即购买指定数量，Shift+点击直接购买64个物品。", List.of(
            new Offer("vanilla", "ROTTEN_FLESH", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "BONE", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "STRING", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "ARROW", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "FEATHER", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "INK_SAC", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "LEATHER", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "SPIDER_EYE", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "GUNPOWDER", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "SLIME_BALL", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "MAGMA_CREAM", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "PRISMARINE_SHARD", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "PRISMARINE_CRYSTALS", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "GLOW_INK_SAC", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "RABBIT_HIDE", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "ENDER_PEARL", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "NAUTILUS_SHELL", "AL_A1", 8, 1, 0),
            new Offer("vanilla", "RABBIT_FOOT", "AL_A1", 8, 1, 0),
            new Offer("vanilla", "BLAZE_ROD", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "PHANTOM_MEMBRANE", "AL_A1", 8, 1, 0),
            new Offer("vanilla", "GHAST_TEAR", "AL_A1", 8, 1, 0),
            new Offer("vanilla", "SHULKER_SHELL", "AL_A1", 8, 1, 0),
            new Offer("vanilla", "SPONGE", "AL_A1", 8, 1, 0),
            new Offer("vanilla", "WITHER_SKELETON_SKULL", "AL_A1", 8, 1, 0),
            new Offer("vanilla", "TRIDENT", "AL_A1", 16, 1, 0),
            new Offer("vanilla", "CHICKEN", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "BEEF", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "PORKCHOP", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "MUTTON", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "RABBIT", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "COD", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "SALMON", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "PUFFERFISH", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "TROPICAL_FISH", "AL_A1", 4, 1, 0)
        ))),
        Map.entry("misc", new Shop("misc", "§x§7§7§f§7§f§f协§x§6§0§f§a§d§a议§x§4§9§f§d§b§5内§x§6§3§f§f§9§3容§x§b§0§f§f§7§5：§x§f§c§f§f§5§7杂物", 10, "§7点击即购买指定数量，Shift+点击直接购买64个物品。", List.of(
            new Offer("vanilla", "STICK", "AL_A1", 4, 5, 0),
            new Offer("vanilla", "SNOWBALL", "AL_A1", 4, 5, 0),
            new Offer("vanilla", "PAPER", "AL_A1", 4, 3, 0),
            new Offer("vanilla", "SUGAR", "AL_A1", 4, 3, 0),
            new Offer("vanilla", "BOWL", "AL_A1", 4, 3, 0),
            new Offer("vanilla", "GLASS_BOTTLE", "AL_A1", 4, 3, 0),
            new Offer("vanilla", "CLAY_BALL", "AL_A1", 4, 3, 0),
            new Offer("vanilla", "BUCKET", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "BOOK", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "BRICK", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "NETHER_BRICK", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "FLINT", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "WATER_BUCKET", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "NAME_TAG", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "LEAD", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "HONEYCOMB", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "HONEY_BOTTLE", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "GLOWSTONE_DUST", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "BLAZE_POWDER", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "FIREWORK_ROCKET", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "MILK_BUCKET", "AL_A1", 8, 1, 0),
            new Offer("vanilla", "LAVA_BUCKET", "AL_A1", 32, 1, 0),
            new Offer("vanilla", "SADDLE", "AL_A1", 32, 1, 0),
            new Offer("vanilla", "BELL", "AL_A1", 32, 1, 0),
            new Offer("vanilla", "FERMENTED_SPIDER_EYE", "AL_A1", 32, 1, 0),
            new Offer("vanilla", "EXPERIENCE_BOTTLE", "AL_A1", 48, 1, 0),
            new Offer("vanilla", "DRAGON_BREATH", "AL_A1", 64, 1, 0)
        ))),
        Map.entry("blocks", new Shop("blocks", "§x§7§7§f§7§f§f协§x§6§0§f§a§d§a议§x§4§9§f§d§b§5内§x§6§3§f§f§9§3容§x§b§0§f§f§7§5：§x§f§c§f§f§5§7方块", 5, "§7点击即购买指定数量，Shift+点击直接购买64个物品。", List.of(
            new Offer("vanilla", "DIRT", "AL_A1", 1, 2, 0),
            new Offer("vanilla", "GRASS_BLOCK", "AL_A1", 1, 2, 0),
            new Offer("vanilla", "COARSE_DIRT", "AL_A1", 1, 2, 0),
            new Offer("vanilla", "COBBLESTONE", "AL_A1", 1, 2, 0),
            new Offer("vanilla", "NETHERRACK", "AL_A1", 1, 2, 0),
            new Offer("vanilla", "STONE", "AL_A1", 1, 2, 0),
            new Offer("vanilla", "DEEPSLATE", "AL_A1", 1, 2, 0),
            new Offer("vanilla", "SAND", "AL_A1", 1, 2, 0),
            new Offer("vanilla", "COBBLED_DEEPSLATE", "AL_A1", 1, 2, 0),
            new Offer("vanilla", "RED_SAND", "AL_A1", 1, 1, 0),
            new Offer("vanilla", "GRAVEL", "AL_A1", 1, 1, 0),
            new Offer("vanilla", "ANDESITE", "AL_A1", 1, 1, 0),
            new Offer("vanilla", "DIORITE", "AL_A1", 1, 1, 0),
            new Offer("vanilla", "GRANITE", "AL_A1", 1, 1, 0),
            new Offer("vanilla", "SANDSTONE", "AL_A1", 1, 1, 0),
            new Offer("vanilla", "BLACKSTONE", "AL_A1", 1, 1, 0),
            new Offer("vanilla", "BASALT", "AL_A1", 1, 1, 0),
            new Offer("vanilla", "CLAY", "AL_A1", 1, 1, 0),
            new Offer("vanilla", "SNOW_BLOCK", "AL_A1", 1, 1, 0),
            new Offer("vanilla", "PODZOL", "AL_A1", 1, 1, 0),
            new Offer("vanilla", "MYCELIUM", "AL_A1", 1, 1, 0),
            new Offer("vanilla", "CRIMSON_NYLIUM", "AL_A1", 1, 1, 0),
            new Offer("vanilla", "WARPED_NYLIUM", "AL_A1", 1, 1, 0),
            new Offer("vanilla", "ROOTED_DIRT", "AL_A1", 1, 1, 0),
            new Offer("vanilla", "MUD", "AL_A1", 1, 1, 0),
            new Offer("vanilla", "RED_SANDSTONE", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "ICE", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "TUFF", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "END_STONE", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "SOUL_SAND", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "SOUL_SOIL", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "MAGMA_BLOCK", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "PACKED_ICE", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "BONE_BLOCK", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "MUDDY_MANGROVE_ROOTS", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "DRIPSTONE_BLOCK", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "POINTED_DRIPSTONE", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "NETHER_WART_BLOCK", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "WARPED_WART_BLOCK", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "DRIED_KELP_BLOCK", "AL_A1", 2, 1, 0),
            new Offer("vanilla", "OBSIDIAN", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "GLOWSTONE", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "SEA_LANTERN", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "CALCITE", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "BOOKSHELF", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "TNT", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "NOTE_BLOCK", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "AMETHYST_BLOCK", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "QUARTZ_BLOCK", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "HONEYCOMB_BLOCK", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "HONEY_BLOCK", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "SLIME_BLOCK", "AL_A1", 4, 1, 0),
            new Offer("vanilla", "GILDED_BLACKSTONE", "AL_A1", 8, 1, 0),
            new Offer("vanilla", "SHROOMLIGHT", "AL_A1", 8, 1, 0),
            new Offer("vanilla", "SCULK_VEIN", "AL_A1", 16, 1, 0),
            new Offer("vanilla", "CRYING_OBSIDIAN", "AL_A1", 32, 1, 0),
            new Offer("vanilla", "BLUE_ICE", "AL_A1", 32, 1, 0),
            new Offer("vanilla", "OCHRE_FROGLIGHT", "AL_A1", 32, 1, 0),
            new Offer("vanilla", "VERDANT_FROGLIGHT", "AL_A1", 32, 1, 0),
            new Offer("vanilla", "PEARLESCENT_FROGLIGHT", "AL_A1", 32, 1, 0),
            new Offer("vanilla", "JUKEBOX", "AL_A1", 32, 1, 0),
            new Offer("vanilla", "RESPAWN_ANCHOR", "AL_A1", 32, 1, 0),
            new Offer("vanilla", "SCULK", "AL_A1", 32, 1, 0),
            new Offer("vanilla", "SCULK_CATALYST", "AL_A1", 48, 1, 0),
            new Offer("vanilla", "SCULK_SHRIEKER", "AL_A1", 64, 1, 0),
            new Offer("vanilla", "SCULK_SENSOR", "AL_A1", 64, 1, 0),
            new Offer("vanilla", "BUDDING_AMETHYST", "AL_A1", 48, 1, 0),
            new Offer("vanilla", "LODESTONE", "AL_A1", 48, 1, 0)
        ))),
        Map.entry("slimefun", new Shop("slimefun", "§x§7§7§f§7§f§f协§x§6§0§f§a§d§a议§x§4§9§f§d§b§5内§x§6§3§f§f§9§3容§x§b§0§f§f§7§5：§x§f§c§f§f§5§7原版粘液科技", 1, "§7点击即购买1次，Shift+点击直接购买64次。", List.of(
            new Offer("slimefun", "ENERGY_REGULATOR", "AL_A1", 1, 1, 0),
            new Offer("slimefun", "ENERGY_CONNECTOR", "AL_A1", 4, 1, 0),
            new Offer("slimefun", "COAL_GENERATOR", "AL_A1", 64, 1, 0),
            new Offer("slimefun", "GG板子", "AL_A1", 1, 1, 10)
        )))
    );
}
